<div class="space-y-6">
    <div><h1 class="font-display text-2xl font-bold text-slate-900">Cobro en destino (COD)</h1><p class="mt-1 text-sm text-slate-500">Consulta cobros recibidos y liquida los que ya fueron cobrados.</p></div>
    @if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ session('error') }}</div>@endif
    <div class="rounded-2xl border bg-white p-5 shadow-sm"><select wire:model.live="status" class="rounded-xl border px-4 py-3"><option value="pending">Pendientes</option><option value="liquidated">Liquidados</option><option value="all">Todos</option></select>
    <div class="mt-5 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-slate-500"><th class="px-3 py-3">Guía</th><th class="px-3 py-3">Destinatario</th><th class="px-3 py-3">Monto</th><th class="px-3 py-3">Cobro</th><th class="px-3 py-3">Liquidación</th><th></th></tr></thead><tbody>
    @forelse($packages as $package)<tr class="border-b last:border-0"><td class="px-3 py-3 font-tracking">{{ $package->tracking_number }}</td><td class="px-3 py-3">{{ $package->recipient_name }}</td><td class="px-3 py-3 font-semibold">${{ number_format((float)$package->cod_amount_usd,2) }}</td><td class="px-3 py-3">{{ $package->cod_collected_at ? $package->cod_collected_at->format('d/m/Y H:i') : 'Pendiente' }}</td><td class="px-3 py-3">{{ $package->cod_liquidated_at ? $package->cod_liquidated_at->format('d/m/Y H:i') : 'Pendiente' }}</td><td class="px-3 py-3 text-right">@if($package->cod_collected_at && $package->cod_status === \App\Models\Package::COD_PENDIENTE)<button wire:click="liquidate({{ $package->id }})" wire:confirm="¿Confirmas la liquidación de este COD?" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Liquidar</button>@endif</td></tr>@empty<tr><td colspan="6" class="px-3 py-8 text-center text-slate-500">Sin registros COD.</td></tr>@endforelse
    </tbody></table></div>{{ $packages->links() }}</div>
</div>
