<?php

return [
    'states' => [
        'Amazonas' => [
            'Puerto Ayacucho',
            'San Fernando de Atabapo',
            'Maroa',
            'San Carlos de Río Negro',
        ],
        'Anzoátegui' => [
            'Barcelona',
            'Puerto La Cruz',
            'Lechería',
            'El Tigre',
            'Anaco',
            'Cantaura',
            'Pariaguán',
            'Guanta',
        ],
        'Apure' => [
            'San Fernando de Apure',
            'Biruaca',
            'Achaguas',
            'Bruzual',
            'Guasdualito',
        ],
        'Aragua' => [
            'Maracay',
            'Turmero',
            'La Victoria',
            'Cagua',
            'Villa de Cura',
            'El Limón',
            'Palo Negro',
        ],
        'Barinas' => [
            'Barinas',
            'Barinitas',
            'Socopó',
            'Ciudad Bolivia',
            'Santa Bárbara',
        ],
        'Bolívar' => [
            'Ciudad Bolívar',
            'Puerto Ordaz',
            'Ciudad Guayana',
            'San Félix',
            'Upata',
            'Tumeremo',
            'Caicara del Orinoco',
            'Santa Elena de Uairén',
        ],
        'Carabobo' => [
            'Valencia',
            'Puerto Cabello',
            'Guacara',
            'Mariara',
            'San Joaquín',
            'Tocuyito',
            'Naguanagua',
        ],
        'Cojedes' => [
            'San Carlos',
            'Tinaquillo',
            'Tinaco',
            'El Baúl',
            'Las Vegas',
        ],
        'Delta Amacuro' => [
            'Tucupita',
            'Pedernales',
            'Casacoima',
        ],
        'Falcón' => [
            'Coro',
            'Punto Fijo',
            'Carirubana',
            'Chichiriviche',
            'Tucacas',
            'Dabajuro',
            'Churuguara',
        ],
        'Guárico' => [
            'San Juan de los Morros',
            'Calabozo',
            'Valle de la Pascua',
            'Zaraza',
            'Altagracia de Orituco',
            'Tucupido',
        ],
        'La Guaira' => [
            'La Guaira',
            'Maiquetía',
            'Catia La Mar',
            'Caraballeda',
            'Naiguatá',
        ],
        'Lara' => [
            'Barquisimeto',
            'Cabudare',
            'Carora',
            'El Tocuyo',
            'Quíbor',
            'Duaca',
        ],
        'Mérida' => [
            'Mérida',
            'El Vigía',
            'Ejido',
            'Tovar',
            'Lagunillas',
            'Mucuchíes',
        ],
        'Miranda' => [
            'Los Teques',
            'Guarenas',
            'Guatire',
            'Charallave',
            'Ocumare del Tuy',
            'Cúa',
            'Santa Teresa del Tuy',
            'Petare',
            'Baruta',
            'Higuerote',
        ],
        'Monagas' => [
            'Maturín',
            'Punta de Mata',
            'Caripe',
            'Caripito',
            'Temblador',
            'Barrancas del Orinoco',
        ],
        'Nueva Esparta' => [
            'La Asunción',
            'Porlamar',
            'Pampatar',
            'Juan Griego',
            'Boca del Río',
        ],
        'Portuguesa' => [
            'Guanare',
            'Acarigua',
            'Araure',
            'Turén',
            'Biscucuy',
            'Villa Bruzual',
        ],
        'Sucre' => [
            'Cumaná',
            'Carúpano',
            'Güiria',
            'Cariaco',
            'Casanay',
            'Río Caribe',
        ],
        'Táchira' => [
            'San Cristóbal',
            'Táriba',
            'Rubio',
            'San Antonio del Táchira',
            'Ureña',
            'La Fría',
            'El Piñal',
        ],
        'Trujillo' => [
            'Trujillo',
            'Valera',
            'Boconó',
            'Carvajal',
            'Motatán',
            'Sabana de Mendoza',
        ],
        'Yaracuy' => [
            'San Felipe',
            'Yaritagua',
            'Chivacoa',
            'Nirgua',
            'Cocorote',
        ],
        'Zulia' => [
            'Maracaibo',
            'Cabimas',
            'Ciudad Ojeda',
            'Santa Rita',
            'Machiques',
            'San Francisco',
            'Villa del Rosario',
            'La Concepción',
            'Los Puertos de Altagracia',
        ],
        'Distrito Capital' => [
            'Caracas',
            'Libertador',
        ],
    ],
];
